// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const feedFollowsCreate = `-- name: FeedFollowsCreate :one
WITH inserted_feed_follow AS (
    INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT
    inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.user_id, inserted_feed_follow.feed_id,
    feeds.name AS feed_name,
    users.name AS user_name
FROM inserted_feed_follow
INNER JOIN feeds ON inserted_feed_follow.feed_id = feeds.id
INNER JOIN users ON inserted_feed_follow.user_id = users.id
`

type FeedFollowsCreateParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type FeedFollowsCreateRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) FeedFollowsCreate(ctx context.Context, arg FeedFollowsCreateParams) (FeedFollowsCreateRow, error) {
	row := q.db.QueryRowContext(ctx, feedFollowsCreate,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollowsCreateRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const feedFollowsDelete = `-- name: FeedFollowsDelete :exec

DELETE FROM feed_follows WHERE feed_id = $1 AND user_id = $2
`

type FeedFollowsDeleteParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) FeedFollowsDelete(ctx context.Context, arg FeedFollowsDeleteParams) error {
	_, err := q.db.ExecContext(ctx, feedFollowsDelete, arg.FeedID, arg.UserID)
	return err
}

const feedFollowsGetForUser = `-- name: FeedFollowsGetForUser :many

SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id, feeds.name AS feed_name, users.name AS user_name
FROM feed_follows
INNER JOIN feeds ON feed_follows.feed_id = feeds.id
INNER JOIN users ON feed_follows.user_id = users.id
WHERE feed_follows.user_id = $1
`

type FeedFollowsGetForUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) FeedFollowsGetForUser(ctx context.Context, userID uuid.UUID) ([]FeedFollowsGetForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, feedFollowsGetForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollowsGetForUserRow
	for rows.Next() {
		var i FeedFollowsGetForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.FeedName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedFollowsReset = `-- name: FeedFollowsReset :exec

DELETE FROM feed_follows
`

func (q *Queries) FeedFollowsReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, feedFollowsReset)
	return err
}
